//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MyDemo.proto
namespace usercmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveC2SMsg")]
  public partial class MoveC2SMsg : global::ProtoBuf.IExtensible
  {
    public MoveC2SMsg() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private float _posX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private float _posY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posY
    {
      get { return _posY; }
      set { _posY = value; }
    }
    private float _posZ;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"posZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posZ
    {
      get { return _posZ; }
      set { _posZ = value; }
    }
    private usercmd.moveType _mType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public usercmd.moveType mType
    {
      get { return _mType; }
      set { _mType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveS2CMsg")]
  public partial class MoveS2CMsg : global::ProtoBuf.IExtensible
  {
    public MoveS2CMsg() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private float _posX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private float _posY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posY
    {
      get { return _posY; }
      set { _posY = value; }
    }
    private float _posZ;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"posZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posZ
    {
      get { return _posZ; }
      set { _posZ = value; }
    }
    private uint _row;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint row
    {
      get { return _row; }
      set { _row = value; }
    }
    private uint _col;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"col", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint col
    {
      get { return _col; }
      set { _col = value; }
    }
    private usercmd.moveType _mType;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"mType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public usercmd.moveType mType
    {
      get { return _mType; }
      set { _mType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginC2SMsg")]
  public partial class LoginC2SMsg : global::ProtoBuf.IExtensible
  {
    public LoginC2SMsg() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginS2CMsg")]
  public partial class LoginS2CMsg : global::ProtoBuf.IExtensible
  {
    public LoginS2CMsg() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SearchC2SMsg")]
  public partial class SearchC2SMsg : global::ProtoBuf.IExtensible
  {
    public SearchC2SMsg() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchS2CMsg")]
  public partial class MatchS2CMsg : global::ProtoBuf.IExtensible
  {
    public MatchS2CMsg() {}
    
    private uint _currentNum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"currentNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint currentNum
    {
      get { return _currentNum; }
      set { _currentNum = value; }
    }
    private uint _totalNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"totalNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint totalNum
    {
      get { return _totalNum; }
      set { _totalNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SearchS2CMsg")]
  public partial class SearchS2CMsg : global::ProtoBuf.IExtensible
  {
    public SearchS2CMsg() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private readonly global::System.Collections.Generic.List<usercmd.SearchS2CMsg.player> _nums = new global::System.Collections.Generic.List<usercmd.SearchS2CMsg.player>();
    [global::ProtoBuf.ProtoMember(2, Name=@"nums", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.SearchS2CMsg.player> nums
    {
      get { return _nums; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"player")]
  public partial class player : global::ProtoBuf.IExtensible
  {
    public player() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameStartS2CMsg")]
  public partial class GameStartS2CMsg : global::ProtoBuf.IExtensible
  {
    public GameStartS2CMsg() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.GameStartS2CMsg.position> _nums = new global::System.Collections.Generic.List<usercmd.GameStartS2CMsg.position>();
    [global::ProtoBuf.ProtoMember(1, Name=@"nums", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.GameStartS2CMsg.position> nums
    {
      get { return _nums; }
    }
  
    private uint _edgenum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"edgenum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint edgenum
    {
      get { return _edgenum; }
      set { _edgenum = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"position")]
  public partial class position : global::ProtoBuf.IExtensible
  {
    public position() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _row;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint row
    {
      get { return _row; }
      set { _row = value; }
    }
    private uint _col;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"col", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint col
    {
      get { return _col; }
      set { _col = value; }
    }
    private usercmd.colorType _color;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public usercmd.colorType color
    {
      get { return _color; }
      set { _color = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeColorS2CMsg")]
  public partial class ChangeColorS2CMsg : global::ProtoBuf.IExtensible
  {
    public ChangeColorS2CMsg() {}
    
    private usercmd.colorType _color;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public usercmd.colorType color
    {
      get { return _color; }
      set { _color = value; }
    }
    private uint _row;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint row
    {
      get { return _row; }
      set { _row = value; }
    }
    private uint _col;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"col", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint col
    {
      get { return _col; }
      set { _col = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameEndS2CMsg")]
  public partial class GameEndS2CMsg : global::ProtoBuf.IExtensible
  {
    public GameEndS2CMsg() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.GameEndS2CMsg.playerMsg> _nums = new global::System.Collections.Generic.List<usercmd.GameEndS2CMsg.playerMsg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"nums", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.GameEndS2CMsg.playerMsg> nums
    {
      get { return _nums; }
    }
  
    private usercmd.colorType _winColor;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"winColor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public usercmd.colorType winColor
    {
      get { return _winColor; }
      set { _winColor = value; }
    }
    private uint _mvpid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mvpid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mvpid
    {
      get { return _mvpid; }
      set { _mvpid = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"playerMsg")]
  public partial class playerMsg : global::ProtoBuf.IExtensible
  {
    public playerMsg() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _cellnum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cellnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cellnum
    {
      get { return _cellnum; }
      set { _cellnum = value; }
    }
    private usercmd.colorType _color;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public usercmd.colorType color
    {
      get { return _color; }
      set { _color = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameEnergyS2CMsg")]
  public partial class GameEnergyS2CMsg : global::ProtoBuf.IExtensible
  {
    public GameEnergyS2CMsg() {}
    
    private usercmd.colorType _color;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public usercmd.colorType color
    {
      get { return _color; }
      set { _color = value; }
    }
    private uint _status;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private usercmd.colorType _lastColor;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lastColor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public usercmd.colorType lastColor
    {
      get { return _lastColor; }
      set { _lastColor = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SynTimeS2CMsg")]
  public partial class SynTimeS2CMsg : global::ProtoBuf.IExtensible
  {
    public SynTimeS2CMsg() {}
    
    private uint _tloop;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tloop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint tloop
    {
      get { return _tloop; }
      set { _tloop = value; }
    }
    private uint _minute;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"minute", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint minute
    {
      get { return _minute; }
      set { _minute = value; }
    }
    private uint _second;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"second", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint second
    {
      get { return _second; }
      set { _second = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateItemsS2CMsg")]
  public partial class CreateItemsS2CMsg : global::ProtoBuf.IExtensible
  {
    public CreateItemsS2CMsg() {}
    
    private uint _row;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint row
    {
      get { return _row; }
      set { _row = value; }
    }
    private uint _col;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"col", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint col
    {
      get { return _col; }
      set { _col = value; }
    }
    private usercmd.itemType _item;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public usercmd.itemType item
    {
      get { return _item; }
      set { _item = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DestroyItemsS2CMsg")]
  public partial class DestroyItemsS2CMsg : global::ProtoBuf.IExtensible
  {
    public DestroyItemsS2CMsg() {}
    
    private uint _row;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint row
    {
      get { return _row; }
      set { _row = value; }
    }
    private uint _col;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"col", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint col
    {
      get { return _col; }
      set { _col = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetItemS2CMsg")]
  public partial class GetItemS2CMsg : global::ProtoBuf.IExtensible
  {
    public GetItemS2CMsg() {}
    
    private usercmd.itemType _item;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public usercmd.itemType item
    {
      get { return _item; }
      set { _item = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseItemC2SMsg")]
  public partial class UseItemC2SMsg : global::ProtoBuf.IExtensible
  {
    public UseItemC2SMsg() {}
    
    private usercmd.itemType _item;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public usercmd.itemType item
    {
      get { return _item; }
      set { _item = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DyeingS2CMsg")]
  public partial class DyeingS2CMsg : global::ProtoBuf.IExtensible
  {
    public DyeingS2CMsg() {}
    
    private uint _passiveId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"passiveId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint passiveId
    {
      get { return _passiveId; }
      set { _passiveId = value; }
    }
    private uint _activeId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"activeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint activeId
    {
      get { return _activeId; }
      set { _activeId = value; }
    }
    private usercmd.colorType _color;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public usercmd.colorType color
    {
      get { return _color; }
      set { _color = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DisDyeingS2CMsg")]
  public partial class DisDyeingS2CMsg : global::ProtoBuf.IExtensible
  {
    public DisDyeingS2CMsg() {}
    
    private uint _passiveId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"passiveId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint passiveId
    {
      get { return _passiveId; }
      set { _passiveId = value; }
    }
    private usercmd.colorType _color;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public usercmd.colorType color
    {
      get { return _color; }
      set { _color = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VirusCreateS2CMsg")]
  public partial class VirusCreateS2CMsg : global::ProtoBuf.IExtensible
  {
    public VirusCreateS2CMsg() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _row;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint row
    {
      get { return _row; }
      set { _row = value; }
    }
    private uint _col;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"col", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint col
    {
      get { return _col; }
      set { _col = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VirusDestroyS2CMsg")]
  public partial class VirusDestroyS2CMsg : global::ProtoBuf.IExtensible
  {
    public VirusDestroyS2CMsg() {}
    
    private uint _row;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint row
    {
      get { return _row; }
      set { _row = value; }
    }
    private uint _col;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"col", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint col
    {
      get { return _col; }
      set { _col = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerImprisonS2CMsg")]
  public partial class PlayerImprisonS2CMsg : global::ProtoBuf.IExtensible
  {
    public PlayerImprisonS2CMsg() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerDizzyS2CMsg")]
  public partial class PlayerDizzyS2CMsg : global::ProtoBuf.IExtensible
  {
    public PlayerDizzyS2CMsg() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerSpeedUpS2CMsg")]
  public partial class PlayerSpeedUpS2CMsg : global::ProtoBuf.IExtensible
  {
    public PlayerSpeedUpS2CMsg() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _speedNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"speedNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint speedNum
    {
      get { return _speedNum; }
      set { _speedNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"DemoTypeCmd")]
    public enum DemoTypeCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveReq", Value=1)]
      MoveReq = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveRes", Value=2)]
      MoveRes = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoginReq", Value=3)]
      LoginReq = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoginRes", Value=4)]
      LoginRes = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SearchReq", Value=5)]
      SearchReq = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SearchRes", Value=6)]
      SearchRes = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameStart", Value=7)]
      GameStart = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeColorRes", Value=9)]
      ChangeColorRes = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameEnd", Value=10)]
      GameEnd = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameEnergy", Value=11)]
      GameEnergy = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameTime", Value=12)]
      GameTime = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemCreate", Value=13)]
      ItemCreate = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemDestroy", Value=14)]
      ItemDestroy = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerGetItem", Value=15)]
      PlayerGetItem = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerUseItem", Value=16)]
      PlayerUseItem = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DyeingCmd", Value=17)]
      DyeingCmd = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DisDyeingCmd", Value=18)]
      DisDyeingCmd = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VirusCreate", Value=19)]
      VirusCreate = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VirusDestroy", Value=20)]
      VirusDestroy = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerImprison", Value=21)]
      PlayerImprison = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerDizzy", Value=22)]
      PlayerDizzy = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MatchRes", Value=23)]
      MatchRes = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerSpeedUp", Value=24)]
      PlayerSpeedUp = 24
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"moveType")]
    public enum moveType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"idle", Value=0)]
      idle = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"left", Value=1)]
      left = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"right", Value=2)]
      right = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"colorType")]
    public enum colorType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"origin", Value=0)]
      origin = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"red", Value=1)]
      red = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"yellow", Value=2)]
      yellow = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"blue", Value=3)]
      blue = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"itemType")]
    public enum itemType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"unknown", Value=0)]
      unknown = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"virus", Value=1)]
      virus = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dyeing", Value=2)]
      dyeing = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"dizzy", Value=3)]
      dizzy = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"speedup", Value=4)]
      speedup = 4
    }
  
}